# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AI4ME Cookbook
author: michael.akridge
copyright: "2025"
logo: docs/images/logo3.png

# Execution settings for notebooks
execute:
  execute_notebooks: "off"
  timeout: -1
  exclude_patterns:
    - '*_notebook.ipynb'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ai4me_cookbook.tex

# Repository settings
repository:
  url: https://github.com/MichaelAkridge-NOAA/ai4me-cookbook  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links

# Enable Reveal.js slides
html:
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  use_revealjs: true  #  Ensure Reveal.js is enabled
  revealjs_theme: "black"  # Options: black, white, night, serif, etc.
  revealjs_scroll: true  #  Allow scrolling inside slides
  revealjs_auto_slide: 5000  #  Auto-slide every 5 seconds (optional)
  favicon: "docs/images/favicon.ico"
  extra_footer: |
    <a href="mailto:michael.akridge@noaa.gov">Contact</a>  <a href="https://github.com/MichaelAkridge-NOAA/ai4me-cookbook"> Github</a><br>

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
  extra_extensions:
    - sphinxcontrib.mermaid
myst_enable_extensions:
  - html_admonition
  - html_image