name: Deploy Jupyter Book
on:
  push:
    branches:
      - main  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the Jupyter Book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          pip install ghp-import
          ghp-import -n -p -f _build/html
